name: PR Code Check

on:
  pull_request:

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"
